# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
    config.vm.host_name = "postgresql"

    config.vm.synced_folder "./vagrant-data", "/vagrant-data"
    config.vm.provision "shell", path: "./postgres-bootstrap.sh"

    config.vm.network "forwarded_port", guest: 5432, host: 15432
end
